config/routes.rb
Rails.application.routes.draw do

  root 'home#index' #our homepage is where we search or click to create new

  post 'contact_search' => 'home#contact_search'
  
  devise_for :users
  resources :contacts
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	
	geocoded_by :full_address
	after_validation :geocode

  def full_address
  	"#{address}, #{city}, #{state}, #{zip}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :image) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :image) }

  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new

    # an array of state postal codes
    @states = %w(HI AK CA OR WA ID UT NV AZ NM CO WY MT ND SD NB KS OK TX LA AR MO IA MN WI IL IN MI OH KY TN MS AL GA FL SC NC VA WV DE MD PA NY NJ CT RI MA VT NH ME DC PR)
    # put them in alphabetical order:
    @states.sort!
  end

  # GET /contacts/1/edit
  def edit
    # see explanation in "new" action
    @states = %w(HI AK CA OR WA ID UT NV AZ NM CO WY MT ND SD NB KS OK TX LA AR MO IA MN WI IL IN MI OH KY TN MS AL GA FL SC NC VA WV DE MD PA NY NJ CT RI MA VT NH ME DC PR)
    @states.sort!
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :business_name, :address, :city, :state, :zip, :phone1, :phone2, :latitude, :longitude, :image, :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  	@contact_found = true
    
    # if we come back here after not finding
    # a matching contact, we're going to change
    # @contact_found to false.
    if params[:contact_found] != nil 
      @contact_found = false
      # this will trigger the notice that no contact was found.
    end
  end

  def contact_search
    # first up, the code for if a 
    # Full Name Search has been attempted
    if params[:search_type] == "FNS"
      name = params[:name]
      # time to make an Active Record call;
      # things get a little tricky, though
      # we took a full name as one string,
      # but we need the first and last names
      # separately, so its substring time
      contact = Contact.find_by(first_name: name[0...name.index(" ")].downcase.capitalize, last_name: name[name.index(" ")+1..name.length-1].downcase.capitalize)

      # what if the search came up with nothing?
      if contact == nil
        # it's back to the homepage, where we'll be
        # posting a notice that no match was found
        redirect_to root_path(contact_found: false)
      else
        # but if a contact was found, let's go to the Show page for that contact
        redirect_to contact
      end

    # next, the code for if a 
    # Last Name Search has been attempted
    elsif params[:search_type] == "LNS"
      # let's just assume that there are more
      # than one contact with the same last name,
      # so we need an Active Record call
      # that returns a collection (i.e., array)
      @contacts = Contact.where(last_name: params[:l_name].downcase.capitalize)

      # if there's only one contact in that
      # collection, then we just need that one
      # contact, so we'll make another Active Record call, 
      # this time just for a single instance
      if @contacts.count == 1
        contact = Contact.find_by(last_name: params[:l_name].downcase.capitalize)

        # and then it's off to the show page for that contact
        redirect_to contact

      # if there's no one by that last name...
      elsif @contacts.count == 0
        # it's back to the homepage,
        # and it's time for the "no contact found" notice
        redirect_to root_path(contact_found: false)
      end      
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :business_name, placeholder: "Business Name (if applicable)", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.email_field :email, placeholder: "Email Address", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :address, placeholder: "Street Address", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :city, placeholder: "City", class: "form-control" %>
  </div>
  <div class="form-group">
    <!-- Users can choose from dropdown of states -->
    <%= f.select(:state, @states.collect { |s| [ s ] }, {:include_blank => 'Select State/Territory'}) %>
  </div>
  <div class="form-group">
    <%= f.text_field :zip, placeholder: "Zip Code", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :phone1, placeholder: "Primary Phone", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :phone2, placeholder: "Secondary Phone", class: "form-control" %>
  </div>
  <div class="form-group">
    <strong>Upload User Image:</strong> <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Business Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone1</th>
      <th>Phone2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %> <%= contact.last_name %></td>
        <td><%= contact.business_name %></td>
        <td><%= contact.address %></td>
        <td><%= contact.city %></td>
        <td><%= contact.state %></td>
        <td><%= contact.zip %></td>
        <td><%= contact.phone1 %></td>
        <td><%= contact.phone2 %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <% if @contact.image_file_name != nil %>
    <div class="col-md-2">
      <h2>
        <%= image_tag @contact.image.url(:thumb) %>
      </h2>
    </div>
  <% end %>
  <div class="col-md-10">
    <h2>
      <%= @contact.first_name %> <%= @contact.last_name %>
    </h2>

    <% if @contact.business_name != nil %>
      <h4>
        <%= @contact.business_name %>
      </h4>
    <% end %>

    <p>
      <%= @contact.email %>
    </p>
  </div>
</div>

<div id="contact-map"></div>

<p>
  <strong>Phone1:</strong>
  <%= @contact.phone1 %>
</p>

<p>
  <strong>Phone2:</strong>
  <%= @contact.phone2 %>
</p>



<%= link_to 'Edit', edit_contact_path(@contact), class: "btn btn-warning" %> 
<%= link_to 'Full Contact List', contacts_path, class: "btn btn-info" %> 
<%= link_to 'Home Page', root_path, class: "btn btn-primary" %>

<%= javascript_tag do %>
   latitude = '<%= j @contact.latitude.to_s %>';
   longitude = '<%= j @contact.longitude.to_s %>';
   address = '<%= j @contact.full_address %>';
   name = '<%= j "#{@contact.first_name} #{@contact.last_name}" %>';
<% end %>

app/views/home/contact_search.html.erb
<!-- We only come to this page if there are multiple people with the same last name (or other search criteria) -->
<p>
	There are several contacts by that last name...
</p>

<!-- A table for now...but we should change this to a grid of wells -->
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Business Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone1</th>
      <th>Phone2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %> <%= contact.last_name %></td>
        <td><%= contact.business_name %></td>
        <td><%= contact.address %></td>
        <td><%= contact.city %></td>
        <td><%= contact.state %></td>
        <td><%= contact.zip %></td>
        <td><%= contact.phone1 %></td>
        <td><%= contact.phone2 %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<div class="row center-it mtop-20">
	<div class="col-md-2 col-md-offset-5">
		<%= link_to 'New Contact', new_contact_path, class: "btn btn-success" %>
	</div>
</div>

<div class="row center-it">
	<div class="col-md-8 col-md-offset-2">
		<!-- If no match was found for their search,
			we let them know and let them try again
		-->
		<% if @contact_found == false %>
			<h4 class="red-text">No Contact Found by That Name</h4>
			<h5 class="red-text">Please try again</h5>
		<% end %>
		<h3>Look Up Your Contacts</h3>

		<!-- Form to search by Full Name -->
		<div id="by_full_name_form">
			<%= form_tag(contact_search_path) do %>
				<div class="form-group">
					<%= text_field_tag :name, nil, placeholder: "Type in Full Name & Press Enter", class: "form-control" %>
					<%= hidden_field_tag :search_type, "FNS" %>
					<!-- FNS = "Full Name Search" -->
				</div>
			<% end %>
		</div>

		<!-- Form to search by Last Name -->
		<div id="by_last_name_form">
			<%= form_tag(contact_search_path) do %>
				<div class="form-group">
					<%= text_field_tag :l_name, nil, placeholder: "or, Type in Last Name & Press Enter", class: "form-control" %>
					<%= hidden_field_tag :search_type, "LNS" %>
					<!-- LNS = "Last Name Search" -->
				</div>
			<% end %>
		</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyContacts</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		&nbsp;
	</header>

	<div class="container">
		<%= yield %>
	</div>
		
	<footer>
		&nbsp;
	</footer>

	<script type="text/javascript"
	    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_maps_api_key'] %>">
	</script>
</body>
</html>